#
# Öppet API för SHL
# Version: 1.0
# Contact: support@shl.se
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ContactInformation
How to get Accredited to home games of the team
.OUTPUTS

Accreditation<PSCustomObject>
#>

function Initialize-Accreditation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ContactInformation}
    )

    Process {
        'Creating PSCustomObject: PSSHL => Accreditation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ContactInformation) {
            throw "invalid value for 'ContactInformation', 'ContactInformation' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'contact_information' = ${ContactInformation}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Accreditation<PSCustomObject>

.DESCRIPTION

Convert from JSON to Accreditation<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Accreditation<PSCustomObject>
#>
function ConvertFrom-JsonToAccreditation {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSHL => Accreditation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Accreditation
        $AllProperties = ('contact_information')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq '{}') {
            # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'contact_information' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'contact_information'))) {
            throw "Error! JSON cannot be serialized due to the required property 'contact_information' missing."
        } else {
            $ContactInformation = $JsonParameters.PSobject.Properties['contact_information'].value
        }

        $PSO = [PSCustomObject]@{
            'contact_information' = ${ContactInformation}
        }

        return $PSO
    }

}

