#
# Öppet API för SHL
# Version: 1.0
# Contact: support@shl.se
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
Id of the team
.PARAMETER Code
The team code of the team
.OUTPUTS

Team<PSCustomObject>
#>

function Initialize-Team {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Code}
    )

    Process {
        'Creating PSCustomObject: PSSHL => Team' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $Code) {
            throw "invalid value for 'Code', 'Code' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            'Id'   = ${Id}
            'Code' = ${Code}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Team<PSCustomObject>

.DESCRIPTION

Convert from JSON to Team<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Team<PSCustomObject>
#>
function ConvertFrom-JsonToTeam {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSSHL => Team' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Team
        $AllProperties = ('Id', 'Code')
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq '{}') {
            # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'Id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'Id'))) {
            throw "Error! JSON cannot be serialized due to the required property 'Id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties['Id'].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match 'Code'))) {
            throw "Error! JSON cannot be serialized due to the required property 'Code' missing."
        } else {
            $Code = $JsonParameters.PSobject.Properties['Code'].value
        }

        $PSO = [PSCustomObject]@{
            'Id'   = ${Id}
            'Code' = ${Code}
        }

        return $PSO
    }

}

