#
# Öppet API för SHL
# <div> <p>För den som önskar finns möjlighet att ta del av nyheter, statistik, video och matchinformation via SHL:s öppna API. Kontakta <a href='mailto:support@shl.se'>support@shl.se</a> med önskemål om detta och för eventuella frågor. Vid förfrågan om åtkomst, vänligen ange tänkt syfte och användningsområde för ditt nyttjande av API:et.</p> <h1>Allmänna villkor</h1> <p>All användning av SHL:s öppna API kräver godkännande av gällande allmänna villkor.</p> <p><a href='/files/terms_v1_0.pdf'>Allmänna villkor (PDF)</a></p> <h1>Dokumentation av API:et</h1> <p>All dokumentation kring API:et finns samlad på denna sida.</p> <h2>Autentisering</h2> <p>All kommunikation med API:et kräver att konsumenten autentiserar sig. Denna autentisering sker enligt OAuth2. Ytterligare detaljer kring autentiseringsförfarandet kommuniceras vid godkännande av förfrågan om åtkomst, samt kommer att publiceras på denna sida.</p> <h2>API-ändpunkter</h2> <p>Nedan följer dokumentation av API:et och dess olika ändpunkter.</p> </div>
# Version: 1.0
# Contact: support@shl.se
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSSHL' -name 'Game' {
    Context 'Game' {
        It 'Initialize-Game' {
            # a simple test to create an object
            #$NewObject = Initialize-Game -GameId "TEST_VALUE" -GameUuid "TEST_VALUE" -Season "TEST_VALUE" -Series "TEST_VALUE" -GameType "TEST_VALUE" -RoundNumber "TEST_VALUE" -StartDateTime "TEST_VALUE" -HomeTeamCode "TEST_VALUE" -HomeTeamResult "TEST_VALUE" -AwayTeamCode "TEST_VALUE" -AwayTeamResult "TEST_VALUE" -PeriodResults "TEST_VALUE" -GameCenterActive "TEST_VALUE" -Played "TEST_VALUE" -Overtime "TEST_VALUE" -PenaltyShots "TEST_VALUE" -TicketUrl "TEST_VALUE" -GameCenterUrlDesktop "TEST_VALUE" -GameCenterUrlMobile "TEST_VALUE" -TvChannels "TEST_VALUE" -Venue "TEST_VALUE"
            #$NewObject | Should -BeOfType Game
            #$NewObject.property | Should -Be 0
        }
    }
}
