#
# Öppet API för SHL
# Version: 1.0
# Contact: support@shl.se
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Get the players, staff members and team facts of selected team

.DESCRIPTION

No description available.

.PARAMETER TeamCode
Team for which to get staff for

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

Teams
#>
function Get-TeamInformation {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true, Mandatory = $false)]
        [String]
        ${TeamCode},
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Get-TeamInformation' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        $LocalVarUri = '/teams/{teamCode}.json'
        if (!$TeamCode) {
            throw "Error! The required parameter `TeamCode` missing when calling getTeamInformation."
        }
        $LocalVarUri = $LocalVarUri.replace('{teamCode}', [System.Web.HTTPUtility]::UrlEncode($TeamCode))

        $LocalVarResult = Invoke-ApiClient -Method 'GET' `
            -Uri $LocalVarUri `
            -Accepts $LocalVarAccepts `
            -ContentTypes $LocalVarContentTypes `
            -Body $LocalVarBodyParameter `
            -HeaderParameters $LocalVarHeaderParameters `
            -QueryParameters $LocalVarQueryParameters `
            -FormParameters $LocalVarFormParameters `
            -CookieParameters $LocalVarCookieParameters `
            -ReturnType 'Teams' `
            -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult['Response']
        }
    }
}

<#
.SYNOPSIS

Get the teams currently active in SHL

.DESCRIPTION

No description available.

.PARAMETER WithHttpInfo

A switch when turned on will return a hash table of Response, StatusCode and Headers instead of just the Response

.OUTPUTS

Fact[]
#>
function Get-teams {
    [CmdletBinding()]
    Param (
        [Switch]
        $WithHttpInfo
    )

    Process {
        'Calling method: Get-teams' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $LocalVarAccepts = @()
        $LocalVarContentTypes = @()
        $LocalVarQueryParameters = @{}
        $LocalVarHeaderParameters = @{}
        $LocalVarFormParameters = @{}
        $LocalVarPathParameters = @{}
        $LocalVarCookieParameters = @{}
        $LocalVarBodyParameter = $null

        $Configuration = Get-Configuration
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/json')

        $LocalVarUri = '/teams.json'

        $LocalVarResult = Invoke-ApiClient -Method 'GET' `
            -Uri $LocalVarUri `
            -Accepts $LocalVarAccepts `
            -ContentTypes $LocalVarContentTypes `
            -Body $LocalVarBodyParameter `
            -HeaderParameters $LocalVarHeaderParameters `
            -QueryParameters $LocalVarQueryParameters `
            -FormParameters $LocalVarFormParameters `
            -CookieParameters $LocalVarCookieParameters `
            -ReturnType 'Fact[]' `
            -IsBodyNullable $false

        if ($WithHttpInfo.IsPresent) {
            return $LocalVarResult
        } else {
            return $LocalVarResult['Response']
        }
    }
}

